---

- name: Minecraft
  hosts: localhost
  user: root
  tasks:

    - user:
        name: minecraft
        shell: /bin/bash
        append: yes

    - name: making backup directory
      file:
        path: /home/minecraft/minecraft-server/backups
        state: directory
        owner: minecraft   


    - name: Install jdk
      apt: pkg=default-jdk state=installed update_cache=true

    - name: Install screen
      apt: pkg=screen state=installed update_cache=true

    - name: Create minecraft dir
      file: state=directory path=/home/minecraft/minecraft-server

    - name: agree to eula
      shell: echo "eula=true" > /home/minecraft/minecraft-server/eula.txt creates=/home/minecraft/minecraft-server/eula.txt

    - name: Download minecraft (1.12.2)
      command: wget -O /home/minecraft/minecraft-server/minecraft_server.jar https://s3.amazonaws.com/Minecraft.Download/versions/1.12.2/minecraft_server.1.12.2.jar chdir=/root/minecraft creates=/home/minecraft/minecraft_server/minecraft-server.jar

    - name: Run minecraft
      command: screen -S minecraft -d -m java -Xmx1024M -Xms1024M -jar /home/minecraft/minecraft-server/minecraft_server.jar nogui chdir=/home/minecraft/minecraft-server/
      
