---

- name: Minecraft
  hosts: localhost
  user: root
  tasks:
    - name: Install jdk
      apt: pkg=default-jdk state=installed update_cache=true

    - name: Install screen
      apt: pkg=screen state=installed update_cache=true

    - name: Create minecraft dir
      file: state=directory path=/root/minecraft

    - name: agree to eula
      shell: echo "eula=true" > /root/minecraft/eula.txt creates=/root/minecraft/eula.txt

    - name: Download minecraft (1.7.4)
      command: wget -O minecraft_server.jar https://s3.amazonaws.com/Minecraft.Download/versions/1.12.2/minecraft_server.1.12.2.jar chdir=/root/minecraft creates=/root/minecraft/minecraft_server.jar

    - name: Run minecraft
      command: screen -S minecraft -d -m java -Xmx1024M -Xms1024M -jar minecraft_server.jar nogui chdir=/root/minecraft
      
